# Docker Compose for Flask App with MongoDB and Nginx
version: "3.8"
services:
  # api 
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: api 
    restart: unless-stopped
    env_file: .env
    environment:
      MONGODB_DATABASE: "MedDict"
      MONGODB_USERNAME: "${MONGODB_USERNAME}"
      MONGODB_PASSWORD: "${MONGODB_PASSWORD}"
      MONGODB_HOSTNAME: "${MONGODB_HOSTNAME}"
    volumes:
      - appdata:/var/www
      - ./data/images:/var/www/images:rw
      - ./data/sounds:/var/www/sounds:rw
    depends_on:
      - mongodb
    networks:
      - backend
    ports: 
      - 5000:5000
  
  web: 
    build: 
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - frontend
    ports:
      - 3000:3000

  # MongoDB
  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped 
    command: mongod --auth 
    # && mongoimport --host mongodb --db MedDict --collection dictionary --type json --file /data/database.json --jsonArray"
    env_file: .env
    environment:
      MONGO_INITDB_DATABASE: "MedDict"
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGODB_DATA_DIR: /data/db
      MONGODB_LOG_DIR: /dev/null
    volumes:
      - ./data/database.json:/data/database.json:ro
      - mongodbdata:/data/db 
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - backend
    ports:
      - '27017-27019:27017-27019'

  # Nginx
  webserver:
    image: nginx:latest
    container_name: webserver
    volumes:
      - ./nginx/${PRODUCTION}.conf:/tmp/nginx.conf
    command: /bin/sh -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    ports:
      - 80:80
      - 433:433
    depends_on:
      - api
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge 
    
  backend: 
    driver: bridge 

volumes:
  mongodbdata:
    driver: local 
  appdata:
    driver: local 
  nginx: 
    driver: local 
